const db = require('../config/database');
class Scan {
  static format(r) { return { id:r.id, filename:r.filename, fileHash:r.file_hash, fileSize:r.file_size, fileType:r.file_type, mimeType:r.mime_type, verdict:r.verdict, riskScore:r.risk_score, analysisDetails:r.analysis_details ? JSON.parse(r.analysis_details):null, createdAt:r.created_at, updatedAt:r.updated_at }; }
  static async create(d) { const q=`INSERT INTO dbo.Scans(filename,file_hash,file_size,file_type,mime_type,verdict,risk_score,analysis_details) OUTPUT INSERTED.* VALUES(@filename,@fileHash,@fileSize,@fileType,@mimeType,@verdict,@riskScore,@analysisDetails)`; const p={...d,verdict:d.verdict||'CLEAN',riskScore:d.riskScore||0,analysisDetails:JSON.stringify(d.analysisDetails||{})}; const r=await db.query(q,p); return this.format(r.recordset[0]); }
  static async findAll(f={}) { const where=['1=1'], p={limit:Math.min(Number(f.limit)||50,100),offset:Math.max(Number(f.offset)||0,0)}; if(f.verdict){where.push('verdict=@verdict');p.verdict=f.verdict;} if(f.search){where.push('(filename LIKE @search OR file_hash LIKE @search)');p.search=`%${f.search}%`;} if(f.dateFrom){where.push('created_at>=@dateFrom');p.dateFrom=f.dateFrom;} if(f.dateTo){where.push('created_at<DATEADD(day,1,@dateTo)');p.dateTo=f.dateTo;} const w=where.join(' AND '); const c=await db.query(`SELECT COUNT(*) total FROM dbo.Scans WHERE ${w}`,p); const r=await db.query(`SELECT * FROM dbo.Scans WHERE ${w} ORDER BY created_at DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`,p); return {scans:r.recordset.map(this.format),pagination:{limit:p.limit,offset:p.offset,total:c.recordset[0].total}}; }
  static async findById(id){const r=await db.query('SELECT * FROM dbo.Scans WHERE id=@id',{id});return r.recordset[0]?this.format(r.recordset[0]):null;}
  static async delete(id){const r=await db.query('DELETE FROM dbo.Scans WHERE id=@id',{id});return r.rowsAffected[0]>0;}
  static async stats(){const total=(await db.query('SELECT COUNT(*) total FROM dbo.Scans')).recordset[0].total; const by=(await db.query('SELECT verdict,COUNT(*) count FROM dbo.Scans GROUP BY verdict')).recordset; const activity=(await db.query(`SELECT CONVERT(date,created_at) date,COUNT(*) count,AVG(risk_score) avgScore FROM dbo.Scans WHERE created_at>=DATEADD(day,-30,SYSDATETIME()) GROUP BY CONVERT(date,created_at) ORDER BY date`)).recordset; return {total,byVerdict:Object.fromEntries(by.map(x=>[x.verdict,x.count])),recentActivity:activity,scoreDistribution:(await db.query(`SELECT CASE WHEN risk_score=0 THEN '0' WHEN risk_score<30 THEN '1-29' WHEN risk_score<50 THEN '30-49' WHEN risk_score<80 THEN '50-79' ELSE '80-100' END range,COUNT(*) count FROM dbo.Scans GROUP BY CASE WHEN risk_score=0 THEN '0' WHEN risk_score<30 THEN '1-29' WHEN risk_score<50 THEN '30-49' WHEN risk_score<80 THEN '50-79' ELSE '80-100' END`)).recordset};}
}
module.exports=Scan;
